name: Keep Repo Active with Empty Commits

on:
  schedule:
    
    - cron: "0 6,14,22 * * *"
  workflow_dispatch:   # allow manual runs too

permissions:
  contents: write   

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push empty commit
        run: |
          git commit --allow-empty -m "chore: keep alive"
          git push
